### ISSUE TITLE
Do I HAVE to use matplotlib version 1.1.0? 

### ISSUE THREAD

**Issue by happykhan** [BeatsonLab-MicrobialGenomics/SeqFindR#1]
Got this error on runtime: 

Traceback (most recent call last):
  File "/usr/local/bin/SeqFindR", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2807, in <module>
    parse_requirements(**requires**), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 594, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: matplotlib==1.1.0

I have matlibplot 1.2.0 installed. Do I have to rollback?

**Comment by mscook** [comment]
Hi Nabil,

I have specified == in setup.py. You could perhaps edit it to >= and python setup.py install
